language: node_js
node_js: 
  - 14.17.3
script:
  - "npm run build"
  - "npm run test:nowatch"

deploy:
  provide: heroku
  api_key: $HEROKU_TOKEN
  app: book-store-tdd-front
  skip_cleanup: true
  on:
  branches:   
    only:      
      - main 
